name: AdvancedChatCRX
main: me.criex.AdvancedChatCRX
version: 1.0.2
api: ["1.1.0"]
author: Criex
description: "An advanced chat plugin with anti-spam, cooldown, and advertisement filtering features."

permissions:
  criex.nochat:
    default: true
    description: "Allows the player to send messages in chat."
  criex.nocmdchat:
    default: op
    description: "Allows the player to bypass the chat cooldown and spam protection."
